--- # this is demo.yaml file 
- hosts: all
  user: ansible
  become: yes
  connection: ssh
 
  tasks:
    - name: installing httpd s/w in webservers
      action: yum name=httpd state=installed
      ignore_errors: yes 
