---
- hosts: all
  user: ansible
  become: true
  connection: ssh

  tasks:
    - name: install jenkins
      yum:
        name: java
        state: present


    - name: install wget command
      yum:
        name: wget
        state: installed


    - name: download jenkins
      get_url: 
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: download jenkiins key
      rpm_key: 
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: install jenkins
      yum:
        name: jenkins
        state: installed

    - name: start jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
